ChatApiSample\Secondary\Persistence\DTO\User:
    type: entity
    repositoryClass: ChatApiSample\Secondary\Persistence\Repository\UserRepository
    table: users
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            unique: true
            length: 255
            options:
                fixed: false
        email:
            type: text
            nullable: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        version:
            type: integer
            nullable: false
            version:
                type: integer
                default: 1
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    lifecycleCallbacks:
        postLoad: [setRole]
