version: '2'

services:
  chat-db:
    container_name: chat-db
    image: mysql:5.7
    volumes:
      - ./mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: chat_root
      MYSQL_DATABASE: chat
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat

  chat-db-admin:
    container_name: chat-db-admin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - chat-db
    ports:
        - "8080:80"
    environment:
        PMA_HOSTS: chat-db

  chat-web:
    container_name: chat-web
    build: ./web
    depends_on:
      - chat-db
    volumes:
      - ../:/var/www/html
    ports:
      - '80:80'
    privileged: true
